### PR TITLE
fixed issue#198

### LINKED ISSUE #198: Solve the errors in json file
https://github.com/Chinmay-03/Hactoberfest-X-MIBCS-2022/blob/main/Aboutme.json
https://github.com/Chinmay-03/Hactoberfest-X-MIBCS-2022/blob/main/Quotes.json

### PR DESCRIPTION
**Pull request by javamultiplex**
closes #198 

Hi,  I have fixed all issues present in both JSON files.  You can review now.

### CODE REVIEW

**Comment by Chinmay-03** [comment]
@javamultiplex  please paste the updated JSON files in vs code to see if they are error-free you will get to know your mistake
check the proper JSON syntax

**Comment by javamultiplex** [comment]
@Chinmay-03  - I have fixed all errors in JSON files and validated them in https://jsonlint.com/ as well as in VS code. I can't see any issue now.

**Review by Chinmay-03 — APPROVED** [review]

**Comment by Chinmay-03** [comment]
> @Chinmay-03 - I have fixed all errors in JSON files and validated them in https://jsonlint.com/ as well as in VS code. I can't see any issue now. Did you see any issue ?

Thanks a lot! @javamultiplex

**Comment by javamultiplex** [comment]
@Chinmay-03  - Thanks for merging the PR.  Can you please label this as **hacktoberfest-accepted**

**Comment by Chinmay-03** [comment]
> @Chinmay-03  - Thanks for merging the PR.  Can you please label this as **hacktoberfest-accepted**

I have already added hacktoberfest accepted lable in repository topic so no need to add here don't worry it will be counted towards hacktoberfest

**Pull request merged**
